url: https://proconcretespokane.com
title: All-Pro Concrete Spokane
phone: (509) 257-4522
logo: 
logo-width: 

google-analytics: G-86ESLR4NPE
site-author: 325 Studio

category-list: [services]

# Privacy Policy and Terms of Service page
state: Washington

# Custom Navbar Colors
navbar-colors:
  bg: "#ffffff"
  menu-color: "#000000"

# Custom button colors
btn-custom-primary:
  text-color: "#ffffff"
  bg: "#2d518b"
  border-color: "#2d518b"
  hover-text-color: "#ffffff"
  hover-bg: "#254270"
  hover-border-color: "#254270"

btn-custom-secondary:
  text-color: "#000000"
  bg: "#ffffff"
  border-color: "#ffffff"
  hover-text-color: "#000000"
  hover-bg: "#e4e9ed"
  hover-border-color: "#000000"

# Call to action box bg color
cta:
  bg: "#2d518b"
  
# Form background color
form: 
  bg: "#CAD5E0"

# Local Business Schema
schema:
  # name: Same as title above
  image: 
  # telephone: Same as phone above
  priceRange: "$$"
  address:
    city: "Spokane"
    state: "Washington"
    country: "USA"
    postalCode: "99201"
  hours:
    dayOfWeek: "Monday-Sunday"
  # url: Same as url above
# End Schema